### ISSUE TITLE
Unable to use loops

### ISSUE THREAD

**Issue by angystardust** [ViaSat/ansible-vsphere#10]
Hi guys. I'm trying to use a loop to upgrade the vmware-tools of some vms in my vsphere cluster.
That's my playbook:

*hosts: localhost*
  *gather_facts: no*
  *vars_files:*
    *- vars/upgrade_vmware-tools.yml*

  *tasks: *

  *- name: Upgrade VmwareTools*
    *local_action:* 
      *module: vsphere*
      *host: "{{ vcenter_host }}"*
      *login: '{{ vcenter_user }}'*
      *password: "{{ vcenter_password }}"*
      *timeout: 60*
      *guest:*
        *name: '{{ item.vmname }}'*
        *state: "{{ item.state }}"*
        *action: "{{ item.action }}"*
        *with_items:*
          *- { vmname: 'vm-001', state: 'running', action: 'upgrade_tools' }*
          *- { vmname: 'vm-002', state: 'running', action: 'upgrade_tools' }*
          *- { vmname: 'vm-003', state: 'running', action: 'upgrade_tools' }*
          *- { vmname: 'vm-004', state: 'running', action: 'upgrade_tools' }*
          *- { vmname: 'vm-005', state: 'running', action: 'upgrade_tools' }*
          *- { vmname: 'vm-006', state: 'running', action: 'upgrade_tools' }*
          *- { vmname: 'vm-007', state: 'running', action: 'upgrade_tools' }*
          *- { vmname: 'vm-008', state: 'running', action: 'upgrade_tools' }*

But sadly the playbook run fails miserably with this error :boom: :

PLAY [localhost] **************************************************************

TASK: [Upgrade VmwareTools] *************************************************** 
fatal: [localhost -> 127.0.0.1] => **One or more undefined variables: 'item' is undefined**

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/upgrade_vmware-toolsNEW.retry

localhost                  : ok=0    changed=0    unreachable=1    failed=0

**Comment by tkinz27** [comment]
I cannot reproduce this currently. The error looks like an ansible variable error though and not a problem with the module. There is no variable called item within the module itself, that variable should be expanded before getting passed to the module. I would just make sure the with_items key is at the right indentation; inline with name and local_action. I can't tell from your post the structure of your play but I know thats bitten me before.

This playbook for instance works fine for me...

```
- hosts: localhost
  gather_facts: no

  tasks:
    - name: upgrade tools
      local_action:
        module: vsphere
        host: "{{ vcenter_host }}"
        login: "{{ vcenter_login }}"
        password: "{{ vcenter_pwd }}"
        timeout: 120
        guest:
          name: "{{ item.name }}"
          state: running
          action: upgrade_tools
      with_items:
        - name: deleteme-1
        - name: deleteme-2
        - name: deleteme-3


TASK: [upgrade tools] *********************************************************
ok: [localhost -> 127.0.0.1] => (item={'name': 'deleteme-1'})
ok: [localhost -> 127.0.0.1] => (item={'name': 'deleteme-2'})
ok: [localhost -> 127.0.0.1] => (item={'name': 'deleteme-3'})
```
